### ISSUE TITLE
有没有关于挖矿方面的变更的文档

### ISSUE THREAD

**Issue by YihaoPeng** [superbitcoin/SBTC-Logo#5]
我想了解一下 getblocktemplate 返回的字段发生了什么更改，智能合约是怎么被包含到 getblocktemplate 中的，以及加入智能合约后，区块结构发生了什么变化。

正在为 BTCPool 添加 SBTC 智能合约支持：
https://github.com/btccom/btcpool/tree/dev

**Comment by bille18** [comment]
**1.块头增加了nHeight,hashStateRoot,hashUTXORoot;3个参数。**
class CBlockHeader
{
public:
    // header
    int32_t nVersion;
    uint256 hashPrevBlock;
    uint256 hashMerkleRoot;
    uint32_t nTime;
    uint32_t nBits;
    uint32_t nNonce;
    **int32_t nHeight;      // sbtc-evm
    uint256 hashStateRoot; // sbtc-evm
    uint256 hashUTXORoot; // sbtc-evm**
.....
}
**2.对应的块索引修改如下:
增加hashStateRoot,hashUTXORoot**

class CBlockIndex{
......
  **uint256 hashStateRoot; // sbtc-vm
    uint256 hashUTXORoot; // sbtc-vm**
}
**3.非常感谢您对SBTC支持!!!**

**Comment by YihaoPeng** [comment]
我有一个疑问，在`CBlockHeader::SerializationOp()`函数里，只要智能合约激活，区块头就会多出三个成员。此外，`CBlockHeader::GetHash()`是直接调用`SerializeHash(*this)`来计算哈希值。我没有在任何地方看到计算哈希值时会忽略那三个成员。

这是不是说，智能合约激活后，区块头哈希值的计算需要包含这三个新成员，参与计算哈希值的区块头由80字节变为148字节？

如果确实是这样，**智能合约激活后，SBTC将与现在所有的SHA256（比特币）矿机不兼容**，因为矿机只能计算固定的80字节的区块头。

@bille18

```
class CBlockHeader
{
    inline void SerializationOp(Stream &s, Operation ser_action)
    {
        READWRITE(this->nVersion);
        READWRITE(hashPrevBlock);
        READWRITE(hashMerkleRoot);
        READWRITE(nTime);
        READWRITE(nBits);
        READWRITE(nNonce);
        if (this->nVersion & (((uint32_t)1) << VERSIONBITS_SBTC_CONTRACT))
        {
            READWRITE(nHeight); // sbtc-evm
            READWRITE(hashStateRoot); // sbtc-evm
            READWRITE(hashUTXORoot); // sbtc-evm
        }
    }
}

uint256 CBlockHeader::GetHash() const
{
    return SerializeHash(*this);
}
```

该回复的内容与以下Issue相同：
https://github.com/superbitcoin/SuperBitcoin/issues/66
